spring:
  application:
    name: deployment-service

  profiles:
    active: local
  kafka:
    bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

clients:
  service-registry:
    base-url: http://localhost:8081
  change-service:
    base-url: http://localhost:8082

app:
  kafka:
    topics:
      deployment-created: deployment.created.v1

