spring:
  application:
    name: deployment-service

  profiles:
    active: local

clients:
  service-registry:
    base-url: http://localhost:8081
  change-service:
    base-url: http://localhost:8082