spring:
  application:
    name: change-service

  profiles:
    active: local
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      probes:
        enabled: true

service-registry:
  base-url: http://localhost:8081

app:
  kafka:
    topics:
      change-recorded: change.recorded.v1

