spring:
  application:
    name: approval-service

  profiles:
    active: local

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

clients:
  deployment-service:
    base-url: http://localhost:8083

app:
  kafka:
    topics:
      deployment-approved: deployment.approved.v1
